#!/bin/zsh

USE_SYSLOG=1
DEFAULT_FUNCTIONS=/usr/local/share/zfsbackup/functions.zsh
. $DEFAULT_FUNCTIONS
[[ -r /etc/zfsbackup/client.conf ]] && . /etc/zfsbackup/client.conf
[[ -r /etc/zfsbackup/${0:t}.conf ]] && . /etc/zfsbackup/${0:t}.conf
[[ -n $USER_FUNCTIONS ]] && [[ -r $USER_FUNCTIONS ]] && . $USER_FUNCTIONS	# allow user functions to override default functions
me="${0:t}:$(pwd)"

zbPATH=$(readlink -f ./path)
zbREALPATH=$(readlink -f ./realpath)

[[ -z "$zbREALPATH" ]] && die "don't know what to bind mount! $(ls -l realpath 2>&1)"
[[ -z "$zbPATH" ]] && die "don't know where to bind mount $zbREALPATH! $(ls -l path 2>&1)"
[[ -d "$zbREALPATH/." ]] || die "'$zbREALPATH' is not a directory!"
[[ "$zbREALPATH[1]" = "/" ]] || die "'$zbREALPATH' is not absolute!"

grep -q " $zbPATH " /proc/mounts && umount -l "$zbPATH"
if grep -q " $zbPATH " /proc/mounts; then
        log warning "could not unmount $zbPATH."
        exit 2
else
        exit 0
fi
