#!/bin/zsh
#
# sets korn.zfsbackup:config[$:BACKUPSERVER] to the name of the sources.d directory just created.

function set_zfsbackup_config_property() {
	echo setting ${PROPPREFIX:-korn.zfsbackup}:config${BACKUPSERVER:+:$BACKUPSERVER}="$zbSOURCENAME" on "$1"...
	zfs set ${PROPPREFIX:-korn.zfsbackup}:config${BACKUPSERVER:+:$BACKUPSERVER}="$zbSOURCENAME" "$1"
}

if [[ "$zbPATH_IS_ZFS" = "1" ]]; then
	# explicitly zfs, being backed up via latest snapshot
	set_zfsbackup_config_property "$zbPATH"
elif [[ "$(findmnt -n -o TARGET "$zbPATH")" = "$zbPATH" ]] && [[ "$(findmnt -n -o FSTYPE "$zbPATH")" = "zfs" ]]; then
	# happens to be zfs, and the backup starts at its root
	set_zfsbackup_config_property "$(findmnt -n -o SOURCE "$zbPATH")"
fi
