#!/bin/zsh
#
# Part of "zfsbackup" (https://github.com/akorn/zfsbackup). Copyright (c) András Korn, 2019. License: GPLv3
#
# Purpose: get rid of bind mounts created by "rsync-restore-preexec"

CONFIG="/etc/zfsbackup/restore-snaphot/$RSYNC_MODULE_NAME"

if [[ -e "$CONFIG" ]]; then
	. "$CONFIG"	# can override $zfs_dataset. TODO: make recursive bind mounting optional (but probably still default)
else
	echo "I don't know what to do without $CONFIG" >&2
	exit 0
fi

if [[ . -ef / ]]; then
	echo "Refusing to operate on root directory" >&2
	exit 1
fi

for i in *(/N); do
	mountpoint -q $i/. && umount -R $i/.
done

rm -f *(@)
exit 0
